Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SherDash.Models;
using SherDash.Services;

namespace SherDash.Controllers;

[Route("announcement")]
public class AnnouncementController : Controller
{
    private readonly JsonDataService<Announcement> _service;

    public AnnouncementController()
    {
        _service = new JsonDataService<Announcement>("announcement.json");
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        var announcement = _service.LoadData();
        return View(announcement);
    }

    [HttpPost("edit")]
    public IActionResult Edit(Announcement announcement)
    {
        return null;
    }
}

Controllers/ChangelogController.cs
using System.Runtime.InteropServices.JavaScript;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SherDash.Models;
using SherDash.Services;
using SherDash.Utils;

namespace SherDash.Controllers;

[Route("changelog")]
public class ChangelogController : Controller
{
    private readonly JsonDataService<Changelog> _service;
    
    public ChangelogController()
    {
        _service = new JsonDataService<Changelog>("changelog.json");
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        var changelog = _service.LoadData().OrderByDescending(c => c.Date).ToList();
        return View(changelog);
    }
    
    // GET: /changelog/add
    [HttpGet("add")]
    public IActionResult Add()
    {
        ViewBag.ChangeType = new SelectList(EnumUtil.GetChangeTypeList(), "Value", "Description");

        var changelog = new Changelog
        {
            Date = DateTime.Today
        };
        
        return View(changelog);
    }
    
    // POST: /changelog/add
    [HttpPost("add")]
    [ValidateAntiForgeryToken]
    public IActionResult Add(Changelog changelog)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.ChangeType = new SelectList(EnumUtil.GetChangeTypeList(), "Value", "Description");
            return View(changelog);
        }

        var log = _service.LoadData();
        changelog.Id = _service.GetNextId(log);
        
        log.Add(changelog);
        _service.SaveData(log);

        return RedirectToAction(nameof(Index));
    }
    
    // POST: /remove/{id}
    [HttpPost("remove/{id}")]
    [ValidateAntiForgeryToken]
    public IActionResult Remove(int id)
    {
        var changelog = _service.LoadData();
        var entry = changelog.FirstOrDefault(e => e.Id == id);

        if (entry != null)
        {
            changelog.Remove(entry);
            _service.SaveData(changelog);
        }

        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SherDash</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SherDash.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SherDash</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Announcement" asp-action="Index">Announcement</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn-dropdown">Customer</button>
                            <div class="dropdown-content">
                                <a href="">Add Customer</a>
                                <a href="">Remove Customer</a>
                                <a href="">Customer List</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container">
        Github | v2.0.0 | <a asp-area="" asp-controller="Changelog" asp-action="Index">Changelog</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>